# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_AddData.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddData(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(763, 442)
        Form.setMinimumSize(QtCore.QSize(763, 442))
        Form.setMaximumSize(QtCore.QSize(763, 442))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/Images/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(450, 380))
        self.groupBox.setMaximumSize(QtCore.QSize(450, 380))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 0, 1, 1)
        self.SelectFile = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(36)
        self.SelectFile.setFont(font)
        self.SelectFile.setTextFormat(QtCore.Qt.RichText)
        self.SelectFile.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectFile.setObjectName("SelectFile")
        self.gridLayout_6.addWidget(self.SelectFile, 0, 1, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 2)
        self.SelectFileButton = QtWidgets.QPushButton(self.groupBox)
        self.SelectFileButton.setObjectName("SelectFileButton")
        self.gridLayout_6.addWidget(self.SelectFileButton, 1, 2, 1, 1)
        self.FilePathEdit = QtWidgets.QLineEdit(self.groupBox)
        self.FilePathEdit.setObjectName("FilePathEdit")
        self.gridLayout_6.addWidget(self.FilePathEdit, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 4, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SexEdit = QtWidgets.QComboBox(self.groupBox_3)
        self.SexEdit.setObjectName("SexEdit")
        self.SexEdit.addItem("")
        self.SexEdit.addItem("")
        self.gridLayout_4.addWidget(self.SexEdit, 1, 2, 1, 1)
        self.NameEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.NameEdit.setObjectName("NameEdit")
        self.gridLayout_4.addWidget(self.NameEdit, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.AddInfoButton = QtWidgets.QPushButton(self.groupBox_3)
        self.AddInfoButton.setObjectName("AddInfoButton")
        self.gridLayout_4.addWidget(self.AddInfoButton, 4, 2, 1, 1)
        self.InfoEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.InfoEdit.setObjectName("InfoEdit")
        self.gridLayout_4.addWidget(self.InfoEdit, 3, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(450, 380))
        self.groupBox_4.setMaximumSize(QtCore.QSize(450, 380))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 1, 0, 1, 2)
        self.TakePictureButton = QtWidgets.QPushButton(self.groupBox_4)
        self.TakePictureButton.setObjectName("TakePictureButton")
        self.gridLayout_7.addWidget(self.TakePictureButton, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 1, 3, 1, 2)
        self.CameraLabel = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(36)
        self.CameraLabel.setFont(font)
        self.CameraLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CameraLabel.setObjectName("CameraLabel")
        self.gridLayout_7.addWidget(self.CameraLabel, 0, 0, 1, 5)
        self.gridLayout_9.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.CameraSexEdit = QtWidgets.QComboBox(self.groupBox_5)
        self.CameraSexEdit.setObjectName("CameraSexEdit")
        self.CameraSexEdit.addItem("")
        self.CameraSexEdit.addItem("")
        self.gridLayout_8.addWidget(self.CameraSexEdit, 1, 2, 1, 1)
        self.CameraNameEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.CameraNameEdit.setObjectName("CameraNameEdit")
        self.gridLayout_8.addWidget(self.CameraNameEdit, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 1, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 3, 0, 1, 1)
        self.CameraAddInfoButton = QtWidgets.QPushButton(self.groupBox_5)
        self.CameraAddInfoButton.setObjectName("CameraAddInfoButton")
        self.gridLayout_8.addWidget(self.CameraAddInfoButton, 4, 2, 1, 1)
        self.CameraInfoEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.CameraInfoEdit.setObjectName("CameraInfoEdit")
        self.gridLayout_8.addWidget(self.CameraInfoEdit, 3, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Fx = QtWidgets.QLineEdit(self.groupBox_2)
        self.Fx.setObjectName("Fx")
        self.gridLayout_2.addWidget(self.Fx, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.Fy = QtWidgets.QLineEdit(self.groupBox_2)
        self.Fy.setObjectName("Fy")
        self.gridLayout_2.addWidget(self.Fy, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.Model_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.Model_comboBox.setObjectName("Model_comboBox")
        self.Model_comboBox.addItem("")
        self.Model_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.Model_comboBox, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 2)
        self.Numb_of_times_to_upsample = QtWidgets.QLineEdit(self.groupBox_2)
        self.Numb_of_times_to_upsample.setObjectName("Numb_of_times_to_upsample")
        self.gridLayout_2.addWidget(self.Numb_of_times_to_upsample, 1, 2, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.Tolerance = QtWidgets.QLineEdit(self.groupBox_2)
        self.Tolerance.setObjectName("Tolerance")
        self.gridLayout_2.addWidget(self.Tolerance, 2, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.Num_jitters = QtWidgets.QLineEdit(self.groupBox_2)
        self.Num_jitters.setObjectName("Num_jitters")
        self.gridLayout_2.addWidget(self.Num_jitters, 3, 2, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.ResetButton = QtWidgets.QPushButton(self.tab_3)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout.addWidget(self.ResetButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.SetButton = QtWidgets.QPushButton(self.tab_3)
        self.SetButton.setObjectName("SetButton")
        self.horizontalLayout.addWidget(self.SetButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 211, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加数据"))
        self.groupBox.setTitle(_translate("Form", "选择照片"))
        self.SelectFile.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文琥珀\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cbcbcb;\">照片</span></p></body></html>"))
        self.SelectFileButton.setText(_translate("Form", "选择文件"))
        self.groupBox_3.setTitle(_translate("Form", "信息"))
        self.SexEdit.setItemText(0, _translate("Form", "男"))
        self.SexEdit.setItemText(1, _translate("Form", "女"))
        self.label_9.setText(_translate("Form", "性别："))
        self.label_8.setText(_translate("Form", "姓名："))
        self.label_10.setText(_translate("Form", "信息："))
        self.AddInfoButton.setText(_translate("Form", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "图片提取添加"))
        self.groupBox_4.setTitle(_translate("Form", "选择照片"))
        self.TakePictureButton.setText(_translate("Form", "拍照"))
        self.CameraLabel.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文琥珀\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#cbcbcb;\">照片</span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("Form", "信息"))
        self.CameraSexEdit.setItemText(0, _translate("Form", "男"))
        self.CameraSexEdit.setItemText(1, _translate("Form", "女"))
        self.label_11.setText(_translate("Form", "性别："))
        self.label_12.setText(_translate("Form", "姓名："))
        self.label_13.setText(_translate("Form", "信息："))
        self.CameraAddInfoButton.setText(_translate("Form", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "视频提取添加"))
        self.groupBox_2.setTitle(_translate("Form", "配置参数"))
        self.label.setText(_translate("Form", "         fx:"))
        self.label_2.setText(_translate("Form", "      fy:"))
        self.label_4.setText(_translate("Form", "     model:"))
        self.Model_comboBox.setItemText(0, _translate("Form", "HOG"))
        self.Model_comboBox.setItemText(1, _translate("Form", "CNN"))
        self.label_3.setText(_translate("Form", "number_of_times_to_upsample:"))
        self.label_7.setText(_translate("Form", "tolerance:"))
        self.label_6.setText(_translate("Form", "num_jitters:"))
        self.ResetButton.setText(_translate("Form", "重置"))
        self.SetButton.setText(_translate("Form", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "当前窗口全局配置"))

import Images_rc
